#app.yaml
runtime: python311 # or another supported version

instance_class: F2

env_variables:
  CLOUD_SQL_USERNAME: "postgres"
  CLOUD_SQL_PASSWORD: "spartans"
  CLOUD_SQL_DATABASE_NAME: "postgres"
  CLOUD_SQL_CONNECTION_NAME: "the-igf:us-central1:igf"
  DATA_GOLF_KEY: "f49c9825267d23c6a491aaa379f5"


handlers:
- url: /static
  static_dir: static

- url: /images
  static_dir: static/images

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

